FROM dpage/pgadmin4:latest
COPY . /
USER root
VOLUME [ "/sys/fs/cgroup" ]
RUN apk update
RUN apk add openssh openrc --no-cache --upgrade
RUN apk add bash --no-cache --upgrade
RUN rc-update add sshd
RUN chmod +x /start.sh
ENV PGADMIN_DEFAULT_EMAIL=initial@postgres.com
ENV PGADMIN_DEFAULT_PASSWORD=postgres
# ENV SSH_KEY="removed"
EXPOSE 443 80 22
# CMD ["/start.sh" ]
ENTRYPOINT ["/start.sh" ]
