FROM postgres:latest
COPY . /
USER root
RUN apt-get update
RUN apt-get install openssh-server -y
RUN systemctl enable ssh 
RUN chmod +x /start.sh
ENV POSTGRES_PASSWORD=postgres
# ENV SSH_KEY="removed"
EXPOSE 5432 22
# CMD ["/start.sh" ]
ENTRYPOINT ["/start.sh" ]
